[MFLOG|0|2023-12-01T21:12:44.595262Z|runtime|7a5bb0ea-7701-40e8-a89d-b131e6430eee]<flow PreLoanFlow step prepare_dataset> failed:
[MFLOG|0|2023-12-01T21:12:46.987013Z|runtime|f1022660-c5f4-43cc-abf6-7f29566084b2]    Internal error
[MFLOG|0|2023-12-01T21:12:46.993100Z|runtime|014abcff-7e23-47ec-8e74-bd2cf18001fa]Traceback (most recent call last):
[MFLOG|0|2023-12-01T21:12:46.993354Z|runtime|a62383fc-3578-45ec-a042-f022a04875d7]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/.venv/lib/python3.11/site-packages/metaflow/cli.py", line 1172, in main
[MFLOG|0|2023-12-01T21:12:46.993917Z|runtime|62185425-7475-4f78-9197-bd8089cf8142]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2023-12-01T21:12:46.994889Z|runtime|01c68161-1f81-4b93-8678-be9abea2165a]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2023-12-01T21:12:46.995316Z|runtime|6d786fb7-a94c-4140-b42e-cd95ffacae71]    return self.main(args, kwargs)
[MFLOG|0|2023-12-01T21:12:46.995753Z|runtime|381dbc7d-f0f9-4053-956b-f98446429170]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-01T21:12:46.996561Z|runtime|de0736b5-e926-4aff-8375-8b1587963e92]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2023-12-01T21:12:46.996852Z|runtime|eb06595d-d134-493e-a9b8-7e3690d394b8]    rv = self.invoke(ctx)
[MFLOG|0|2023-12-01T21:12:46.997313Z|runtime|ab46cfb1-5b2b-4eba-8a43-f0e7178572a4]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-01T21:12:46.997693Z|runtime|9d13e760-7691-47cb-aa53-27a68b38b718]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2023-12-01T21:12:46.998037Z|runtime|68e3c289-6d64-4e96-9a87-ae3e3996dd2c]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2023-12-01T21:12:46.998363Z|runtime|f8961192-abaa-428c-8321-f54f359b2cd7]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-01T21:12:46.998580Z|runtime|c0a1908a-a851-495a-be41-736308b90abc]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2023-12-01T21:12:46.998766Z|runtime|01dc1249-01cf-4fbf-ae66-03fe74555f07]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2023-12-01T21:12:47.866660Z|runtime|a5324bf2-b95b-462b-a429-ab869607d8c6]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-01T21:12:47.866992Z|runtime|87984091-8c88-476d-b9f1-27db000aa865]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2023-12-01T21:12:47.867097Z|runtime|2c23d56b-0871-4e5d-b7b5-d510a7dad5c3]    return callback(args, kwargs)
[MFLOG|0|2023-12-01T21:12:47.867183Z|runtime|80f4e438-711d-4bd6-9782-22968cb731ed]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-01T21:12:47.867278Z|runtime|3704e243-1eff-4c7d-8c64-994b131ea3c8]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2023-12-01T21:12:47.867353Z|runtime|709a87a0-3598-4582-afcc-061a9cc6f164]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2023-12-01T21:12:47.867422Z|runtime|198b802d-8b44-40b1-896a-305bb1f0be93]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2023-12-01T21:12:47.867490Z|runtime|ef1a8b7c-665d-4897-a6ac-975c32ec578e]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/.venv/lib/python3.11/site-packages/metaflow/cli.py", line 581, in step
[MFLOG|0|2023-12-01T21:12:47.867571Z|runtime|2dce9524-378d-45f9-a04b-9f057f51f798]    task.run_step(
[MFLOG|0|2023-12-01T21:12:47.867638Z|runtime|bd157800-c6a4-4900-aa09-e2e7f98ec6e0]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/.venv/lib/python3.11/site-packages/metaflow/task.py", line 583, in run_step
[MFLOG|0|2023-12-01T21:12:47.867851Z|runtime|a163b0d6-d05a-41f8-bd03-07b0260258a2]    self._exec_step_function(step_func)
[MFLOG|0|2023-12-01T21:12:47.867967Z|runtime|fae4eb13-47a2-4d5e-b619-97a420d895d6]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/.venv/lib/python3.11/site-packages/metaflow/task.py", line 57, in _exec_step_function
[MFLOG|0|2023-12-01T21:12:47.868073Z|runtime|e1e708e5-e7d7-4ffe-b92e-8314896afbd6]    step_function()
[MFLOG|0|2023-12-01T21:12:47.868152Z|runtime|f2f43638-84c6-4548-989e-807291c6e2dd]  File "/Users/cameronwalcott/Desktop/mlfe-project/project/src/project/preloan.py", line 86, in prepare_dataset
[MFLOG|0|2023-12-01T21:12:47.868245Z|runtime|00a030cc-23d8-4584-aba0-7e24b40d90cc]    pickle.dump(X_train, file)
[MFLOG|0|2023-12-01T21:12:47.868340Z|runtime|ec189b3e-7846-4147-b01e-2e68e714384f]    ^^^^^^
[MFLOG|0|2023-12-01T21:12:47.868412Z|runtime|c924afbc-eb00-4f9f-8589-e48530f82d8f]NameError: name 'pickle' is not defined
[MFLOG|0|2023-12-01T21:12:47.868494Z|runtime|301b88c2-ae9d-40b7-9752-8357edbcbc9c]
[MFLOG|0|2023-12-01T21:12:47.869398Z|runtime|2cb34ab1-99c7-493b-a849-629b01e5ac9a]Task failed.